#' A function that summarizes the output of a bootstrap procedure in a mediation analysis
#'
#' This function summarizes the columns in an output dataset generated by a bootstrap procedure.
#' @param output a dataset generated by a bootstrap procedure
#' @keywords mediation bootstrap
#' @export
#' @examples
#' mediation.summary()

mediation.summary <- function(output) {
  for (i in 1:ncol(output)){
    m <- mean(output[,i])
    l <- quantile(output[,i],.025)
    u <- quantile(output[,i],.975)
    
    if (l*u > 0) {
      sig <- " -> significant"
    } else  {
      sig <- " -> non-significant"
    }
    
    if (m>0){
      p <- length(which(output[,i]<0)) / length(output[,i])
      p2 <- ", % of distribution negative: "
    } else {
      p <- length(which(output[,i]>0)) / length(output[,i])
      p2 <- ", % of distribution positive: "
    }
    returntext <- paste("mean: ",round(m,3),", [",round(l,3),"; ",round(u,3),"]",sig,p2,round(p,3),sep="")
    
    q <- paste(names(output)[i], returntext, sep=": ")
    print(q)
  }
}